/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiwumRouteImport } from './routes/archiwum'
import { Route as DzisRouteImport } from './routes/dzis'
import { Route as NowaRouteImport } from './routes/nowa'
import { Route as ObserwacjaRouteImport } from './routes/obserwacja'
import { Route as PobierzRouteImport } from './routes/pobierz'
import { Route as SelekcjaRouteImport } from './routes/selekcja'
import { Route as StandardRouteImport } from './routes/standard'
import { Route as Tabela23RouteImport } from './routes/tabela-23'
import { Route as AnalizaIdRouteImport } from './routes/analiza.$id'
import { Route as ApiScanRouteImport } from './routes/api.scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiwumRoute = ArchiwumRouteImport.update({
  id: '/archiwum',
  path: '/archiwum',
  getParentRoute: () => rootRouteImport,
} as any)
const DzisRoute = DzisRouteImport.update({
  id: '/dzis',
  path: '/dzis',
  getParentRoute: () => rootRouteImport,
} as any)
const NowaRoute = NowaRouteImport.update({
  id: '/nowa',
  path: '/nowa',
  getParentRoute: () => rootRouteImport,
} as any)
const ObserwacjaRoute = ObserwacjaRouteImport.update({
  id: '/obserwacja',
  path: '/obserwacja',
  getParentRoute: () => rootRouteImport,
} as any)
const PobierzRoute = PobierzRouteImport.update({
  id: '/pobierz',
  path: '/pobierz',
  getParentRoute: () => rootRouteImport,
} as any)
const SelekcjaRoute = SelekcjaRouteImport.update({
  id: '/selekcja',
  path: '/selekcja',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardRoute = StandardRouteImport.update({
  id: '/standard',
  path: '/standard',
  getParentRoute: () => rootRouteImport,
} as any)
const Tabela23Route = Tabela23RouteImport.update({
  id: '/tabela-23',
  path: '/tabela-23',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalizaIdRoute = AnalizaIdRouteImport.update({
  id: '/analiza/$id',
  path: '/analiza/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archiwum': typeof ArchiwumRoute
  '/dzis': typeof DzisRoute
  '/nowa': typeof NowaRoute
  '/obserwacja': typeof ObserwacjaRoute
  '/pobierz': typeof PobierzRoute
  '/selekcja': typeof SelekcjaRoute
  '/standard': typeof StandardRoute
  '/tabela-23': typeof Tabela23Route
  '/analiza/$id': typeof AnalizaIdRoute
  '/api/scan': typeof ApiScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archiwum': typeof ArchiwumRoute
  '/dzis': typeof DzisRoute
  '/nowa': typeof NowaRoute
  '/obserwacja': typeof ObserwacjaRoute
  '/pobierz': typeof PobierzRoute
  '/selekcja': typeof SelekcjaRoute
  '/standard': typeof StandardRoute
  '/tabela-23': typeof Tabela23Route
  '/analiza/$id': typeof AnalizaIdRoute
  '/api/scan': typeof ApiScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archiwum': typeof ArchiwumRoute
  '/dzis': typeof DzisRoute
  '/nowa': typeof NowaRoute
  '/obserwacja': typeof ObserwacjaRoute
  '/pobierz': typeof PobierzRoute
  '/selekcja': typeof SelekcjaRoute
  '/standard': typeof StandardRoute
  '/tabela-23': typeof Tabela23Route
  '/analiza/$id': typeof AnalizaIdRoute
  '/api/scan': typeof ApiScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archiwum'
    | '/dzis'
    | '/nowa'
    | '/obserwacja'
    | '/pobierz'
    | '/selekcja'
    | '/standard'
    | '/tabela-23'
    | '/analiza/$id'
    | '/api/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archiwum'
    | '/dzis'
    | '/nowa'
    | '/obserwacja'
    | '/pobierz'
    | '/selekcja'
    | '/standard'
    | '/tabela-23'
    | '/analiza/$id'
    | '/api/scan'
  id:
    | '__root__'
    | '/'
    | '/archiwum'
    | '/dzis'
    | '/nowa'
    | '/obserwacja'
    | '/pobierz'
    | '/selekcja'
    | '/standard'
    | '/tabela-23'
    | '/analiza/$id'
    | '/api/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiwumRoute: typeof ArchiwumRoute
  DzisRoute: typeof DzisRoute
  NowaRoute: typeof NowaRoute
  ObserwacjaRoute: typeof ObserwacjaRoute
  PobierzRoute: typeof PobierzRoute
  SelekcjaRoute: typeof SelekcjaRoute
  StandardRoute: typeof StandardRoute
  Tabela23Route: typeof Tabela23Route
  AnalizaIdRoute: typeof AnalizaIdRoute
  ApiScanRoute: typeof ApiScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archiwum': {
      id: '/archiwum'
      path: '/archiwum'
      fullPath: '/archiwum'
      preLoaderRoute: typeof ArchiwumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dzis': {
      id: '/dzis'
      path: '/dzis'
      fullPath: '/dzis'
      preLoaderRoute: typeof DzisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nowa': {
      id: '/nowa'
      path: '/nowa'
      fullPath: '/nowa'
      preLoaderRoute: typeof NowaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obserwacja': {
      id: '/obserwacja'
      path: '/obserwacja'
      fullPath: '/obserwacja'
      preLoaderRoute: typeof ObserwacjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pobierz': {
      id: '/pobierz'
      path: '/pobierz'
      fullPath: '/pobierz'
      preLoaderRoute: typeof PobierzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selekcja': {
      id: '/selekcja'
      path: '/selekcja'
      fullPath: '/selekcja'
      preLoaderRoute: typeof SelekcjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard': {
      id: '/standard'
      path: '/standard'
      fullPath: '/standard'
      preLoaderRoute: typeof StandardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabela-23': {
      id: '/tabela-23'
      path: '/tabela-23'
      fullPath: '/tabela-23'
      preLoaderRoute: typeof Tabela23RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analiza/$id': {
      id: '/analiza/$id'
      path: '/analiza/$id'
      fullPath: '/analiza/$id'
      preLoaderRoute: typeof AnalizaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiwumRoute: ArchiwumRoute,
  DzisRoute: DzisRoute,
  NowaRoute: NowaRoute,
  ObserwacjaRoute: ObserwacjaRoute,
  PobierzRoute: PobierzRoute,
  SelekcjaRoute: SelekcjaRoute,
  StandardRoute: StandardRoute,
  Tabela23Route: Tabela23Route,
  AnalizaIdRoute: AnalizaIdRoute,
  ApiScanRoute: ApiScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
